version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - crypto-net

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - crypto-net

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - crypto-net


  websocket-client:
    build:
      context: ./websocket-client
    container_name: websocket-client
    networks:
      - crypto-net

  spark-stream-job:
    build:
      context: ./spark/stream_processing
    container_name: spark-stream-job
    environment:
      SPARK_JOB: stream_processing
      SPARK_MONGO_PACKAGE: "org.mongodb.spark:mongo-spark-connector_2.12:3.0.1"
      SPARK_KAFKA_PACKAGE: "org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0"
    networks:
      - crypto-net

  spark-batch-job:
    build:
      context: ./spark/batch_processing
    container_name: spark-batch-job
    environment:
      SPARK_JOB: batch_processing
      SPARK_MONGO_PACKAGE: "org.mongodb.spark:mongo-spark-connector_2.12:3.0.1"
    networks:
      - crypto-net

  fastapi-app:
    build:
      context: ./fastapi-app
    container_name: fastapi-app
    ports:
      - "8000:8000"
    networks:
      - crypto-net

networks:
  crypto-net:
    name: crypto-net
